import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import PromoContent from "../components/PromoContent";
import PromoImage from "../components/PromoImage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Snap!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <PromoContent />
        <PromoImage />
      </main>
    </div>
  );
}
